# Generated by Django 4.2.6 on 2023-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casamento", "0002_listacasamento_tipo_lista"),
    ]

    operations = [
        migrations.AddField(
            model_name="listacasamento",
            name="codigo_seguranca",
            field=models.CharField(
                blank=True,
                help_text="Para gerar um codigo clique aqui https://www.lastpass.com/pt/features/password-generator",
                max_length=300,
                null=True,
                verbose_name="Codigo de segurança",
            ),
        ),
        migrations.AddField(
            model_name="listacasamento",
            name="item_ja_escolhido",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Se não estiver marcado o Item ainda não foi escolhido",
                null=True,
                verbose_name="Item disponivel ou não",
            ),
        ),
    ]
