# Generated by Django 5.1.4 on 2024-12-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0003_listacasamento_codigo_seguranca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacasamento',
            name='quem_escolheu',
            field=models.CharField(blank=True, help_text='Nome de quem escolheu o item', max_length=400, null=True, verbose_name='Quem escolheu'),
        ),
    ]
